#!/bin/bash

# Скрипт на построчноу чтение из файла
# Имя скрипта и путь до файла из которого читаем 
./test.sh /home/ubuntupc/Downloads/access.log

FILE=$1
while read LINE; do
     echo "Это строка: $LINE"
     sleep 2
done < $FILE



# Построчное чтение файла 
while read LINE
    do COMMAND
done < FILE

# Бесконечный цикл (do {тело цикла} done)
while true
do
        echo hello
        sleep 2
done

# Просмотр файла в режиме реального времени: 
tail -f 

# Перенаправления 
2>/dev/null  - ошибки 
1>my.log     - вывод результата
